import { expect, test, type Page } from "@playwright/test";
import { testMp3 } from "../fixtures/audio";

const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
async function signIn(page: Page, email: string, password: string) { await page.goto("/sign-in"); await page.getByLabel("Email").fill(email); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page).toHaveURL(/\/admin\/artists$/); }
async function uploadImage(page: Page, name: string) {
  const response = await page.request.post("/api/admin/media", { headers: { Origin: "http://127.0.0.1:3000" }, multipart: { kind: "IMAGE", file: { name, mimeType: "image/png", buffer: png } } });
  expect(response.ok()).toBe(true);
  const id = (await response.json()).id as string;
  await expect.poll(async () => (await (await page.request.get(`/api/admin/media/${id}`)).json()).status).toBe("READY");
  return id;
}

test("Editor completes local audio ingest, Track freezing, and Podcast file_id delivery", async ({ page }) => {
  const browserErrors: string[] = []; page.on("pageerror", (error) => browserErrors.push(error.message)); page.on("console", (message) => { if (message.type() === "error" && !message.text().includes("422 (Unprocessable Entity)")) browserErrors.push(message.text()); });
  const suffix = Date.now(); const firstName = `audio-a-${suffix}.mp3`; const secondName = `audio-b-${suffix}.mp3`; const artistName = `Audio E2E Artist ${suffix}`; const trackTitle = `Audio Track ${suffix}`; const podcastTitle = `Audio Podcast ${suffix}`; const apiKey = process.env.LEGACY_API_KEY_A!;
  await signIn(page, process.env.SEED_EDITOR_EMAIL!, process.env.SEED_EDITOR_PASSWORD!); await page.getByRole("link", { name: "Media", exact: true }).click();
  await page.getByText("Upload MP3", { exact: true }).locator("input").setInputFiles({ name: firstName, mimeType: "audio/mpeg", buffer: testMp3() }); await expect(page.getByText(firstName, { exact: true })).toBeVisible(); await page.getByLabel("Kind filter").selectOption("AUDIO"); const card = page.locator(".media-card").filter({ hasText: firstName }); await expect(card).toContainText("READY"); await expect(card).toContainText("0:00"); await card.click(); await expect(page.locator(".preview audio")).toHaveAttribute("src", /\/legacy-audio\/.+-high\.mp3$/);
  const first = (await (await page.request.get("/api/admin/media?kind=AUDIO")).json()).items.find((asset: { originalFilename: string }) => asset.originalFilename === firstName); expect(first).toBeTruthy();
  await page.getByRole("link", { name: "Artists", exact: true }).click(); await page.getByRole("link", { name: "New artist" }).click(); await page.getByLabel("Artist name").fill(artistName); await page.getByRole("button", { name: "Create draft" }).click(); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.locator(".summary-strip")).toContainText("PUBLISHED");
  await page.getByRole("link", { name: "Tracks", exact: true }).click(); await page.getByRole("link", { name: "Create Track" }).click(); await page.getByLabel("Title").fill(trackTitle); await page.getByLabel("Search Artists").fill(artistName); const artistValue = await page.getByLabel("Primary Artist").locator("option").filter({ hasText: artistName }).getAttribute("value"); await page.getByLabel("Primary Artist").selectOption(artistValue!); await page.getByLabel("Label").selectOption({ label: "Steyoyoke" }); await page.getByRole("button", { name: "Create draft" }).click(); const trackLegacyId = (await page.locator(".summary-strip .mono").first().textContent())!.trim(); await page.getByLabel("Audio", { exact: true }).selectOption(first.id); await page.getByRole("button", { name: "Save draft" }).click(); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.getByTestId("legacy-preview")).toContainText(trackTitle);
  let legacy = (await (await page.request.get(`/index.php/cms/api/${trackLegacyId}?filter=tracks&type=track`, { headers: { "X-Csrf-Token": apiKey } })).json()).tracks[0]; expect(legacy.file_id).toBe(first.legacyAudioId);
  const audioPicker = page.locator(".media-picker").filter({ has: page.getByRole("heading", { name: "Audio" }) }); await audioPicker.locator('input[type="file"]').setInputFiles({ name: secondName, mimeType: "audio/mpeg", buffer: testMp3() }); await expect(audioPicker).toContainText(secondName); const second = (await (await page.request.get("/api/admin/media?kind=AUDIO")).json()).items.find((asset: { originalFilename: string }) => asset.originalFilename === secondName); await page.getByRole("button", { name: "Save draft" }).click(); legacy = (await (await page.request.get(`/index.php/cms/api/${trackLegacyId}?filter=tracks&type=track`, { headers: { "X-Csrf-Token": apiKey } })).json()).tracks[0]; expect(legacy.file_id).toBe(first.legacyAudioId); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.getByText("Draft matches published revision")).toBeVisible(); legacy = (await (await page.request.get(`/index.php/cms/api/${trackLegacyId}?filter=tracks&type=track`, { headers: { "X-Csrf-Token": apiKey } })).json()).tracks[0]; expect(legacy.file_id).toBe(second.legacyAudioId);
  const artworkId = await uploadImage(page, `audio-podcast-${suffix}.png`); await page.getByRole("link", { name: "Podcasts", exact: true }).click(); await page.getByRole("link", { name: "Create Podcast" }).click(); await page.getByLabel("Title").fill(podcastTitle); await page.getByLabel("Search Artists").fill(artistName); const podcastArtist = await page.getByLabel("Primary Artist").locator("option").filter({ hasText: artistName }).getAttribute("value"); await page.getByLabel("Primary Artist").selectOption(podcastArtist!); await page.getByLabel("Label").selectOption({ label: "Steyoyoke" }); await page.getByLabel("Episode Date").fill("2026-09-10"); await page.getByRole("button", { name: "Create draft" }).click(); const podcastLegacyId = (await page.locator(".summary-strip .mono").first().textContent())!.trim(); await page.getByLabel("Artwork").selectOption(artworkId); await page.getByRole("button", { name: "Save Draft" }).click(); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.locator(".alert.error")).toContainText("Audio is required"); await page.getByLabel("Audio", { exact: true }).selectOption(second.id); await page.getByRole("button", { name: "Save Draft" }).click(); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.getByTestId("legacy-preview")).toContainText(podcastTitle); legacy = (await (await page.request.get(`/index.php/cms/api/${podcastLegacyId}?filter=tracks&type=podcast`, { headers: { "X-Csrf-Token": apiKey } })).json()).tracks[0]; expect(legacy.file_id).toBe(`/legacy-audio/${second.legacyAudioId}-high.mp3`); const delivery = await page.request.get(legacy.file_id, { headers: { Range: "bytes=0-31" } }); expect(delivery.status()).toBe(206); expect(delivery.headers()["content-type"]).toBe("audio/mpeg"); expect(browserErrors).toEqual([]);
});

test("Viewer can inspect AUDIO but cannot upload or replace it", async ({ page }) => { await signIn(page, process.env.SEED_VIEWER_EMAIL!, process.env.SEED_VIEWER_PASSWORD!); await page.getByRole("link", { name: "Media", exact: true }).click(); await page.getByLabel("Kind filter").selectOption("AUDIO"); await page.locator(".media-card").first().click(); await expect(page.locator("audio").first()).toBeVisible(); await expect(page.getByText("Upload MP3", { exact: true })).toHaveCount(0); const denied = await page.request.post("/api/admin/media", { multipart: { kind: "AUDIO", file: { name: "denied.mp3", mimeType: "audio/mpeg", buffer: testMp3() } } }); expect(denied.status()).toBe(403); });
