import { expect, test, type Page } from "@playwright/test";

const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
async function signIn(page: Page, email: string, password: string) { await page.goto("/sign-in"); await page.getByLabel("Email").fill(email); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page).toHaveURL(/\/admin\/artists$/); }

test("Editor uploads local images and Artist delivery follows frozen artwork revisions", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message)); page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  const suffix = Date.now(); const firstName = `media-a-${suffix}.png`; const secondName = `media-b-${suffix}.png`; const artistName = `Media E2E Artist ${suffix}`; const apiKey = process.env.LEGACY_API_KEY_A!;
  await signIn(page, process.env.SEED_EDITOR_EMAIL!, process.env.SEED_EDITOR_PASSWORD!); await page.getByRole("link", { name: "Media", exact: true }).click(); await expect(page).toHaveURL(/\/admin\/media$/);
  await page.getByText("Upload image", { exact: true }).locator("input").setInputFiles({ name: firstName, mimeType: "image/png", buffer: png }); await expect(page.getByText(firstName, { exact: true })).toBeVisible(); await expect(page.locator(".media-card").first()).toContainText("READY"); await expect(page.locator(".preview")).toContainText("ORIGINAL"); await expect(page.locator(".preview")).toContainText("LEGACY_THUMB_80");
  const assets = await (await page.request.get("/api/admin/media")).json(); const first = assets.find((asset: { originalFilename: string }) => asset.originalFilename === firstName); expect(first).toBeTruthy();
  await page.getByRole("link", { name: "Artists", exact: true }).click(); await page.getByRole("link", { name: "New artist" }).click(); await page.getByLabel("Artist name").fill(artistName); await page.getByRole("button", { name: "Create draft" }).click(); await page.getByLabel("Artwork").selectOption(first.id); await page.getByRole("button", { name: "Save draft" }).click(); const legacyId = await page.locator(".summary-strip .mono").first().textContent(); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.getByTestId("legacy-preview")).toContainText(first.compatibilityFilename);
  let legacy = (await (await page.request.get(`/index.php/cms/api/${legacyId}?filter=artists`, { headers: { "X-Csrf-Token": apiKey } })).json()).artists[0]; expect(legacy.image).toContain(first.compatibilityFilename); expect((await page.request.get(legacy.image)).ok()).toBe(true);
  await page.locator('.media-picker input[type="file"]').setInputFiles({ name: secondName, mimeType: "image/png", buffer: png }); await expect(page.getByText(secondName, { exact: true })).toBeVisible(); const second = (await (await page.request.get("/api/admin/media")).json()).find((asset: { originalFilename: string }) => asset.originalFilename === secondName); expect(second).toBeTruthy(); await page.getByRole("button", { name: "Save draft" }).click();
  legacy = (await (await page.request.get(`/index.php/cms/api/${legacyId}?filter=artists`, { headers: { "X-Csrf-Token": apiKey } })).json()).artists[0]; expect(legacy.image).toContain(first.compatibilityFilename); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.getByTestId("legacy-preview")).toContainText(second.compatibilityFilename); legacy = (await (await page.request.get(`/index.php/cms/api/${legacyId}?filter=artists`, { headers: { "X-Csrf-Token": apiKey } })).json()).artists[0]; expect(legacy.image).toContain(second.compatibilityFilename); expect(errors).toEqual([]);
});

test("Viewer can inspect Media but cannot upload or replace", async ({ page }) => {
  await signIn(page, process.env.SEED_VIEWER_EMAIL!, process.env.SEED_VIEWER_PASSWORD!); await page.getByRole("link", { name: "Media", exact: true }).click(); await expect(page.getByRole("heading", { name: "Media", exact: true })).toBeVisible(); await expect(page.locator('input[type="file"]')).toHaveCount(0);
  const denied = await page.request.post("/api/admin/media", { multipart: { file: { name: "denied.png", mimeType: "image/png", buffer: png } } }); expect(denied.status()).toBe(403);
});
