import { createPublishedArtist } from "./artist-fixtures";
import { expect, test, type Page } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
async function login(page: Page, viewer = false) { await page.goto('/sign-in'); await page.waitForLoadState('networkidle'); await page.getByLabel('Email').fill(process.env[viewer ? 'SEED_VIEWER_EMAIL' : 'SEED_EDITOR_EMAIL']!); await page.getByLabel('Password').fill(process.env[viewer ? 'SEED_VIEWER_PASSWORD' : 'SEED_EDITOR_PASSWORD']!); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await page.waitForURL('**/admin/artists'); }
async function reload(page: Page, name: string) { await Promise.all([page.waitForEvent('load'), page.getByRole('button', { name, exact: true }).click()]); }
test('Podcast Create/Edit saves chapters atomically and preserves publication lifecycle', async ({ page }) => {
  test.setTimeout(90000); await login(page); const suffix=Date.now(); const name=`Podcast UX TEST ${suffix}`; const primary=await createPublishedArtist(page,name);
  await page.goto('/admin/podcasts/new'); await page.getByLabel('Title',{exact:true}).fill(name); const combo=page.getByRole('combobox',{name:'Primary Artist',exact:true});await combo.fill(name);await page.getByRole('option').filter({hasText:name}).first().waitFor();await combo.press('ArrowDown');await combo.press('Enter');await page.getByRole('combobox',{name:'Label',exact:true}).selectOption({label:'Steyoyoke'});await page.getByLabel('Episode Date',{exact:true}).fill('2026-09-14');
  await page.getByLabel('Complete tracklist').fill(`${name} - Track 1 1;00:00\n${name} - Track 2 2;00:01`);await page.getByRole('button',{name:'Validate tracklist',exact:true}).click();

  const post=page.waitForResponse(r=>r.url().endsWith('/api/admin/podcasts')&&r.request().method()==='POST');await page.getByRole('button',{name:'Create podcast',exact:true}).click();const result=await post;expect(result.status()).toBe(201);const episode=await result.json();await page.waitForURL('**/admin/podcasts/'+episode.id);await expect(page.getByLabel('Complete tracklist')).toContainText('Track 2 2;00:01');
  await page.getByRole('button',{name:'Publish now',exact:true}).click();await expect(page.locator('.editor-form [role=alert]')).toContainText('Artwork is required');
  const headers={Origin:new URL(page.url()).origin};const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
  const image=await page.request.post('/api/admin/media',{headers,multipart:{file:{name:`podcast-${suffix}.png`,mimeType:'image/png',buffer:png}}});expect(image.status()).toBe(201);const art=await image.json();await expect.poll(async()=> (await(await page.request.get('/api/admin/media/'+art.id)).json()).status).toBe('READY');
  const audio=await page.request.post('/api/admin/media',{headers,multipart:{kind:'AUDIO',file:{name:`podcast-${suffix}.mp3`,mimeType:'audio/mpeg',buffer:execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=440:duration=3','-f','mp3','pipe:1'])}}});expect(audio.status()).toBe(201);const sound=await audio.json();
  const attach=await page.request.patch('/api/admin/podcasts/'+episode.id,{headers,data:{title:name,primaryArtistId:primary.id,labelId:episode.labelId,episodeDate:'2026-09-14',artworkAssetId:art.id,audioAssetId:sound.id,expectedWorkingVersion:1}});expect(attach.status()).toBe(200);await page.reload();await expect(page.locator('audio')).toHaveCount(1);await expect(page.getByLabel('Duration',{exact:true})).toHaveCount(0);
  await reload(page,'Publish now');const legacy=async()=> (await(await page.request.get(`/index.php/cms/api/${episode.legacyId}?filter=tracks&type=podcast`,{headers:{'X-Csrf-Token':process.env.LEGACY_API_KEY_A!}})).json()).tracks;
  expect((await legacy())[0].artist_feature_times.map((c:{title:string})=>c.title)).toEqual(['Track 1','Track 2']);
  await page.getByLabel('Title',{exact:true}).fill(name+' edited');await page.getByLabel('Complete tracklist').fill(`${name} - Track 2 1;00:00\n${name} - Track 1 2;00:01`);await page.getByRole('button',{name:'Validate tracklist',exact:true}).click();const writes:string[]=[];page.on('request',r=>{if(r.method()==='PATCH'||r.method()==='PUT')writes.push(r.method());});await reload(page,'Save changes');expect(writes).toEqual(['PATCH']);expect((await legacy())[0].title).toBe(name);expect((await legacy())[0].artist_feature_times[0].title).toBe('Track 1');await reload(page,'Publish now');expect((await legacy())[0].artist_feature_times[0].title).toBe('Track 2');
  await page.getByLabel('Schedule time',{exact:true}).fill('2099-01-01T12:00');await reload(page,'Schedule');await expect(page.locator('.status')).toContainText('SCHEDULED');await reload(page,'Cancel schedule');await reload(page,'Unpublish');await expect(page.locator('.status')).toContainText('UNPUBLISHED');
  await page.getByRole('button',{name:'Delete / archive podcast',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await page.getByRole('button',{name:'Delete / archive podcast',exact:true}).click();await page.getByRole('button',{name:'Confirm archive',exact:true}).click();await page.waitForURL('**/admin/podcasts');expect(await legacy()).toEqual([]);await page.goto('/admin/podcasts/'+episode.id);await expect(page.getByRole('button',{name:'Save changes',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Restore podcast',exact:true}).click();await reload(page,'Confirm restore');await expect(page.locator('.status')).toContainText('UNPUBLISHED');
});
test('Viewer cannot mutate Podcasts',async({page})=>{await login(page,true);await page.goto('/admin/podcasts');await expect(page.getByRole('link',{name:'Create Podcast',exact:true})).toHaveCount(0);await page.locator('a.table-row').first().click();await expect(page.getByRole('button',{name:'Save changes',exact:true})).toHaveCount(0);const r=await page.request.patch('/api/admin/podcasts/'+new URL(page.url()).pathname.split('/').at(-1),{headers:{Origin:new URL(page.url()).origin},data:{}});expect(r.status()).toBe(403);});


test('Bulk validation, stale-save protection and responsive Create/Edit preview', async ({page}) => {
  await login(page);const fixture=readFileSync(new URL('../fixtures/podcast-tracklist.txt',import.meta.url),'utf8');const name=`Tracklist TEST ${Date.now()}`;const primary=await createPublishedArtist(page,name);
  await page.goto('/admin/podcasts/new');await page.waitForLoadState('networkidle');await page.getByLabel('Title',{exact:true}).fill(name);const combo=page.getByRole('combobox',{name:'Primary Artist',exact:true});await combo.fill(name);await page.getByRole('listbox').getByRole('option',{name,exact:true}).click();await page.getByRole('combobox',{name:'Label',exact:true}).selectOption({label:'Steyoyoke'});
  const input=page.getByLabel('Complete tracklist');await input.fill(fixture);const save=page.getByRole('button',{name:'Create podcast',exact:true});await expect(save).toBeDisabled();await page.getByRole('button',{name:'Validate tracklist',exact:true}).click();await expect(page.locator('.tracklist-success')).toContainText('12 tracks detected');await expect(page.getByRole('table',{name:'Validated tracklist'}).getByRole('row')).toHaveCount(13);
  await input.fill(fixture.replace('1;00:00','1:00:00'));await expect(page.locator('.tracklist-stale')).toHaveText('Tracklist changed — validate again.');await expect(save).toBeDisabled();await expect(page.getByRole('table',{name:'Validated tracklist'})).toHaveCount(0);await page.getByRole('button',{name:'Validate tracklist',exact:true}).click();await expect(page.locator('.tracklist-errors')).toContainText('Did you mean: 1;00:00?');await page.locator('.tracklist-errors').getByRole('button',{name:'Line 1',exact:true}).click();await expect(input).toBeFocused();
  await input.fill(fixture);await page.getByRole('button',{name:'Validate tracklist',exact:true}).click();
  for(const width of [1440,430,390]) {await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);expect(await page.locator('.tracklist-preview').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);}
  const response=page.waitForResponse(r=>r.url().endsWith('/api/admin/podcasts')&&r.request().method()==='POST');await save.click();const saved=await response;expect(saved.status()).toBe(201);const episode=await saved.json();await page.waitForURL('**/admin/podcasts/'+episode.id);await expect(input).toHaveValue(fixture.trim());await expect(page.getByRole('button',{name:'Save changes',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Validate tracklist',exact:true}).click();
  for(const width of [1440,430,390]) {await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);expect(await page.locator('.tracklist-preview').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);}
  await input.fill('');await page.getByRole('button',{name:'Validate tracklist',exact:true}).click();await expect(page.locator('.tracklist-success')).toContainText('Intentionally empty');await reload(page,'Save changes');await expect(input).toHaveValue('');
});
