import { expect, test, type Page } from "@playwright/test";

async function signIn(page: Page, email: string, password: string) {
  await page.goto("/sign-in"); await page.getByLabel("Email").fill(email); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page).toHaveURL(/\/admin\/artists$/);
}

async function uploadArtwork(page: Page, name: string) {
  const response = await page.request.post("/api/admin/media", { headers: { Origin: "http://127.0.0.1:3000" }, multipart: { file: { name, mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64") } } }); const body = await response.text(); if (!response.ok()) throw new Error(`Media upload ${response.status()}: ${body}`); return JSON.parse(body).id as string;
}

async function createPublishedTrack(page: Page, artistName: string, title: string) {
  await page.getByRole("link", { name: "Tracks", exact: true }).click(); await expect(page).toHaveURL(/\/admin\/tracks$/); await page.getByRole("link", { name: "Create Track" }).click(); await expect(page).toHaveURL(/\/admin\/tracks\/new$/); await page.getByLabel("Title").fill(title); await page.getByLabel("Search Artists").fill(artistName); await expect(page.getByLabel("Search Artists")).toHaveValue(artistName); const artistValue = await page.getByLabel("Primary Artist").locator("option").filter({ hasText: artistName }).getAttribute("value"); await page.getByLabel("Primary Artist").selectOption(artistValue!); await page.getByLabel("Label").selectOption({ label: "Inner Symphony" }); await page.getByRole("button", { name: "Create draft" }).click();
  await expect(page).toHaveURL(/\/admin\/tracks\/[0-9a-f-]+$/); const id = page.url().split("/").at(-1)!; await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.locator(".summary-strip")).toContainText("PUBLISHED"); return id;
}

test("Editor completes Release publication with exact TrackRevision freezing", async ({ page }) => {
  const browserErrors: string[] = []; page.on("pageerror", (error) => browserErrors.push(error.message)); page.on("console", (message) => { if (message.type() === "error") browserErrors.push(message.text()); });
  const suffix = Date.now(); const artistName = `Release E2E Artist ${suffix}`; const releaseTitle = `Steyoyoke Release E2E ${suffix}`; const draftTitle = `Release E2E Updated ${suffix}`; const trackATitle = `Release Track A ${suffix}`; const trackARevision2 = `${trackATitle} r2`; const trackBTitle = `Release Track B ${suffix}`; const apiKey = process.env.LEGACY_API_KEY_A!;
  await signIn(page, process.env.SEED_EDITOR_EMAIL!, process.env.SEED_EDITOR_PASSWORD!);
  const artworkId = await uploadArtwork(page, `release-${suffix}.png`);
  await page.getByRole("link", { name: "New artist" }).click(); await page.getByLabel("Artist name").fill(artistName); await page.getByRole("button", { name: "Create draft" }).click(); await expect(page).toHaveURL(/\/admin\/artists\/[0-9a-f-]+$/); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.locator(".summary-strip")).toContainText("PUBLISHED");
  const trackAId = await createPublishedTrack(page, artistName, trackATitle); const trackBId = await createPublishedTrack(page, artistName, trackBTitle);
  await page.getByRole("link", { name: "Releases", exact: true }).click(); await expect(page).toHaveURL(/\/admin\/releases$/); await page.getByRole("link", { name: "Create Release" }).click(); await expect(page).toHaveURL(/\/admin\/releases\/new$/); await page.getByLabel("Title").fill(releaseTitle); await page.getByLabel("Search Artists").fill(artistName); const releaseArtistValue = await page.getByLabel("Primary Artist").locator("option").filter({ hasText: artistName }).getAttribute("value"); await page.getByLabel("Primary Artist").selectOption(releaseArtistValue!); await page.getByLabel("Label").selectOption({ label: "Inner Symphony" }); await page.getByLabel("Release Date").fill("2026-07-08"); await page.getByRole("button", { name: "Create draft" }).click();
  await expect(page).toHaveURL(/\/admin\/releases\/[0-9a-f-]+$/); const releaseUrl = page.url(); const legacyId = await page.locator(".summary-strip .mono").first().textContent();
  await page.getByLabel("Available Track", { exact: true }).selectOption(trackAId); await page.getByRole("button", { name: "Add Track" }).click(); await page.getByLabel("Available Track", { exact: true }).selectOption(trackBId); await page.getByRole("button", { name: "Add Track" }).click(); await page.getByRole("button", { name: "Move Track 2 up" }).click(); await page.getByRole("button", { name: "Save Draft" }).click(); await expect(page.locator(".summary-strip")).toContainText("v3"); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.locator(".alert.error")).toContainText("Artwork is required"); browserErrors.length = 0; await page.getByLabel("Artwork").selectOption(artworkId); await page.getByRole("button", { name: "Save Draft" }).click(); await expect(page.locator(".summary-strip")).toContainText("v4");
  let api = await page.request.get(`/index.php/cms/api/${legacyId}?filter=releases`, { headers: { "X-Csrf-Token": apiKey } }); expect((await api.json()).releases).toEqual([]);
  await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.locator(".summary-strip")).toContainText("PUBLISHED"); api = await page.request.get(`/index.php/cms/api/${legacyId}?filter=releasecomplete`, { headers: { "X-Csrf-Token": apiKey } }); let delivered = (await api.json()).releasecomplete; expect(delivered["0"].title).toBe(`Release E2E ${suffix}`); expect(delivered.tracks.map((track: { title: string }) => track.title)).toEqual([trackBTitle, trackATitle]);
  await page.getByLabel("Title", { exact: true }).fill(draftTitle); await page.getByRole("button", { name: "Move Track 2 up" }).click(); await page.getByRole("button", { name: "Save Draft" }).click(); await expect(page.locator(".summary-strip")).toContainText("v6"); await expect(page.getByText("Unpublished changes")).toBeVisible();
  api = await page.request.get(`/index.php/cms/api/${legacyId}?filter=releasecomplete`, { headers: { "X-Csrf-Token": apiKey } }); delivered = (await api.json()).releasecomplete; expect(delivered["0"].title).toBe(`Release E2E ${suffix}`); expect(delivered.tracks.map((track: { title: string }) => track.title)).toEqual([trackBTitle, trackATitle]);
  await page.goto(`/admin/tracks/${trackAId}`); await page.getByLabel("Title", { exact: true }).fill(trackARevision2); await page.getByRole("button", { name: "Save draft" }).click(); await expect(page.locator(".summary-strip")).toContainText("v2"); await expect(page.getByText("Unpublished changes")).toBeVisible(); await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.getByText("Draft matches published revision")).toBeVisible(); await page.goto(releaseUrl); await expect(page.getByText("Track has changed since this Release was last published.")).toBeVisible();
  api = await page.request.get(`/index.php/cms/api/${legacyId}?filter=releasecomplete`, { headers: { "X-Csrf-Token": apiKey } }); delivered = (await api.json()).releasecomplete; expect(delivered.tracks.map((track: { title: string }) => track.title)).toEqual([trackBTitle, trackATitle]);
  await page.getByRole("button", { name: "Publish now" }).click(); await expect(page.getByText("Draft matches published revision")).toBeVisible(); api = await page.request.get(`/index.php/cms/api/${legacyId}?filter=releasecomplete`, { headers: { "X-Csrf-Token": apiKey } }); delivered = (await api.json()).releasecomplete; expect(delivered["0"].title).toBe(draftTitle); expect(delivered.tracks.map((track: { title: string }) => track.title)).toEqual([trackARevision2, trackBTitle]);
  await page.getByLabel("Schedule time").fill("2099-01-01T12:00"); await page.getByRole("button", { name: "Schedule", exact: true }).click(); await expect(page.locator(".summary-strip")).toContainText("SCHEDULED"); await page.getByRole("button", { name: "Cancel schedule" }).click(); await expect(page.locator(".summary-strip")).toContainText("PUBLISHED");
  await page.getByRole("button", { name: "Unpublish" }).click(); await expect(page.locator(".summary-strip")).toContainText("UNPUBLISHED"); await page.getByRole("button", { name: "Archive" }).click(); await expect(page.locator(".summary-strip")).toContainText("ARCHIVED"); await page.getByRole("button", { name: "Restore" }).click(); await expect(page.locator(".summary-strip")).toContainText("UNPUBLISHED"); expect(browserErrors).toEqual([]);
});

test("Viewer can inspect Releases but cannot mutate them", async ({ page }) => {
  await signIn(page, process.env.SEED_VIEWER_EMAIL!, process.env.SEED_VIEWER_PASSWORD!); await page.getByRole("link", { name: "Releases", exact: true }).click(); await expect(page).toHaveURL(/\/admin\/releases$/); await expect(page.getByRole("heading", { name: "Releases" })).toBeVisible(); await expect(page.getByRole("link", { name: "Create Release" })).toHaveCount(0); const row = page.locator("a.table-row").first(); await expect(row).toBeVisible(); await row.click(); await expect(page).toHaveURL(/\/admin\/releases\/[0-9a-f-]+$/); await expect(page.getByRole("button", { name: "Save Draft" })).toHaveCount(0); await expect(page.getByRole("button", { name: "Publish now" })).toHaveCount(0); const denied = await page.request.patch(`/api/admin/releases/${page.url().split("/").at(-1)}`, { data: {} }); expect(denied.status()).toBe(403);
});
