import { afterAll, beforeEach, describe, expect, it } from "vitest";
import type { Actor } from "@/lib/authorization";
import { prisma } from "@/lib/prisma";
import { createArtist, publishArtist } from "@/modules/artists/service";
import { createAndProcessAudio, getMediaReferences, purgeEligibleMedia } from "@/modules/media/service";
import { localStorage, type StorageProvider } from "@/modules/media/storage";
import { createTrack, getTrack, publishTrack, updateTrackDraft } from "@/modules/tracks/service";
import { createPodcast, getPodcast, publishPodcast, updatePodcastDraft } from "@/modules/podcasts/service";
import { serializeLegacyTrack } from "@/modules/tracks/legacy";
import { serializeLegacyPodcast } from "@/modules/podcasts/legacy";
import { GET as getAudio } from "@/app/legacy-audio/[filename]/route";
import { testMp3 } from "../fixtures/audio";

class MemoryStorage implements StorageProvider { files = new Map<string, Buffer>(); async put(key: string, bytes: Buffer) { if (this.files.has(key)) throw new Error("collision"); this.files.set(key, bytes); } async read(key: string) { const value = this.files.get(key); if (!value) throw new Error("missing"); return value; } async exists(key: string) { return this.files.has(key); } async delete(key: string) { this.files.delete(key); } }

let editor: Actor; let admin: Actor; let labelId: string; let artistId: string; let artworkId: string;
beforeEach(async () => {
  await prisma.$executeRawUnsafe('TRUNCATE TABLE "media_audit_logs", "media_variants", "media_assets", "release_audit_logs", "release_revision_tracks", "release_revisions", "release_tracks", "releases", "podcast_audit_logs", "podcast_chapter_revisions", "podcast_episode_revisions", "podcast_chapters", "podcast_episodes", "track_audit_logs", "track_revisions", "tracks", "audit_logs", "artist_revisions", "artists", "accounts", "sessions", "verifications", "users", "labels" RESTART IDENTITY CASCADE');
  const [editorUser, adminUser] = await Promise.all([prisma.user.create({ data: { name: "Editor", email: "audio-editor@test.local", role: "EDITOR", emailVerified: true } }), prisma.user.create({ data: { name: "Admin", email: "audio-admin@test.local", role: "ADMIN", emailVerified: true } })]); editor = { userId: editorUser.id, role: "EDITOR" }; admin = { userId: adminUser.id, role: "ADMIN" };
  labelId = (await prisma.label.create({ data: { name: "Steyoyoke", slug: "steyoyoke", legacyValue: "STEYOYOKE" } })).id; const artist = await createArtist(editor, { name: "Audio Artist" }); await publishArtist(editor, artist.id, { expectedWorkingVersion: 1 }); artistId = artist.id;
  artworkId = (await prisma.mediaAsset.create({ data: { kind: "IMAGE", status: "READY", provider: "LOCAL", sourceStorageKey: `tests/${crypto.randomUUID()}.jpg`, compatibilityFilename: `${crypto.randomUUID()}.jpg`, originalFilename: "cover.jpg", mimeType: "image/jpeg", byteSize: 3, sha256Checksum: "a".repeat(64), width: 1, height: 1, createdById: editor.userId } })).id;
});
afterAll(async () => prisma.$disconnect());
const upload = (storage: StorageProvider = new MemoryStorage(), name = "tone.mp3") => createAndProcessAudio(editor, { name, bytes: testMp3() }, storage);

describe("audio media, publication, and compatibility", () => {
  it("ingests a valid MP3 with immutable metadata, checksum, storage, ID, and audit", async () => { const storage = new MemoryStorage(); const asset = await upload(storage, "../unsafe name.mp3"); expect(asset).toMatchObject({ kind: "AUDIO", status: "READY", mimeType: "audio/mpeg", width: null, height: null, compatibilityFilename: null, durationMs: 287 }); expect(asset.legacyAudioId).toMatch(/^[0-9a-f-]{36}$/); expect(asset.sourceStorageKey).toMatch(/^audio\/[0-9a-f-]+\/source\.mp3$/); expect(storage.files.get(asset.sourceStorageKey)).toEqual(testMp3()); expect(asset.sha256Checksum).toMatch(/^[a-f0-9]{64}$/); expect(await prisma.mediaAuditLog.count({ where: { mediaAssetId: asset.id, action: "MEDIA_UPLOAD" } })).toBe(1); await expect(prisma.mediaAsset.update({ where: { id: asset.id }, data: { durationMs: 9 } })).rejects.toThrow(/immutable/); });

  it("rejects corrupt/non-audio bytes without a partial asset", async () => { await expect(createAndProcessAudio(editor, { name: "fake.mp3", bytes: Buffer.from("not audio") }, new MemoryStorage())).rejects.toMatchObject({ code: "AUDIO_INVALID" }); expect(await prisma.mediaAsset.count({ where: { kind: "AUDIO" } })).toBe(0); });

  it("serves full and safe byte-range compatibility audio", async () => { const asset = await upload(localStorage); const filename = `${asset.legacyAudioId}-high.mp3`; const full = await getAudio(new Request(`http://local/legacy-audio/${filename}`), { params: Promise.resolve({ filename }) } as never); expect(full.status).toBe(200); expect(full.headers.get("content-type")).toBe("audio/mpeg"); expect(full.headers.get("accept-ranges")).toBe("bytes"); const partial = await getAudio(new Request(`http://local/legacy-audio/${filename}`, { headers: { Range: "bytes=0-31" } }), { params: Promise.resolve({ filename }) } as never); expect(partial.status).toBe(206); expect(partial.headers.get("content-range")).toBe(`bytes 0-31/${testMp3().length}`); expect((await partial.arrayBuffer()).byteLength).toBe(32); expect((await getAudio(new Request("http://local/legacy-audio/../secret"), { params: Promise.resolve({ filename: "../secret" }) } as never)).status).toBe(404); await localStorage.delete(asset.sourceStorageKey); });

  it("keeps Track audio optional, enforces kind/readiness, and freezes raw file_id", async () => { const optional = await createTrack(editor, { title: "No Audio", primaryArtistId: artistId, labelId }); await publishTrack(editor, optional.id, { expectedWorkingVersion: 1 }); const [a, b] = await Promise.all([upload(), upload(undefined, "second.mp3")]); await expect(createTrack(editor, { title: "Wrong Kind", primaryArtistId: artistId, labelId, audioAssetId: artworkId })).rejects.toMatchObject({ code: "AUDIO_NOT_READY" }); const track = await createTrack(editor, { title: "Audio Track", primaryArtistId: artistId, labelId, audioAssetId: a.id }); await publishTrack(editor, track.id, { expectedWorkingVersion: 1 }); await updateTrackDraft(editor, track.id, { title: track.title, primaryArtistId: artistId, labelId, audioAssetId: b.id, expectedWorkingVersion: 1 }); let detail = await getTrack(editor, track.id); expect(detail.publishedRevision?.audioAssetId).toBe(a.id); expect(serializeLegacyTrack(detail.publishedRevision!, detail.legacyId).file_id).toBe(a.legacyAudioId); await publishTrack(editor, track.id, { expectedWorkingVersion: 2 }); detail = await getTrack(editor, track.id); expect(serializeLegacyTrack(detail.publishedRevision!, detail.legacyId).file_id).toBe(b.legacyAudioId); expect((await getMediaReferences(editor, a.id)).some(({ type }) => type === "TRACK_AUDIO_REVISION")).toBe(true); });

  it("requires READY AUDIO for Podcast, freezes it, and emits configured URL file_id", async () => { const [a, b] = await Promise.all([upload(), upload(undefined, "podcast-b.mp3")]); const missing = await createPodcast(editor, { title: "Missing Audio", primaryArtistId: artistId, labelId, episodeDate: "2026-09-10", artworkAssetId: artworkId }); await expect(publishPodcast(editor, missing.id, { expectedWorkingVersion: 1 })).rejects.toMatchObject({ code: "AUDIO_REQUIRED" }); const failed = await prisma.mediaAsset.create({ data: { kind: "AUDIO", status: "FAILED", provider: "LOCAL", sourceStorageKey: `tests/${crypto.randomUUID()}.mp3`, legacyAudioId: crypto.randomUUID(), originalFilename: "failed.mp3", mimeType: "audio/mpeg", byteSize: 1, sha256Checksum: "f".repeat(64), durationMs: 1, createdById: editor.userId } }); await prisma.podcastEpisode.update({ where: { id: missing.id }, data: { audioAssetId: failed.id } }); await expect(publishPodcast(editor, missing.id, { expectedWorkingVersion: 1 })).rejects.toMatchObject({ code: "AUDIO_NOT_READY" }); await prisma.podcastEpisode.update({ where: { id: missing.id }, data: { audioAssetId: artworkId } }); await expect(publishPodcast(editor, missing.id, { expectedWorkingVersion: 1 })).rejects.toMatchObject({ code: "AUDIO_NOT_READY" }); const podcast = await createPodcast(editor, { title: "Audio Podcast", primaryArtistId: artistId, labelId, episodeDate: "2026-09-10", artworkAssetId: artworkId, audioAssetId: a.id }); await publishPodcast(editor, podcast.id, { expectedWorkingVersion: 1 }); await updatePodcastDraft(editor, podcast.id, { title: podcast.title, primaryArtistId: artistId, labelId, episodeDate: "2026-09-10", artworkAssetId: artworkId, audioAssetId: b.id, expectedWorkingVersion: 1 }); let detail = await getPodcast(editor, podcast.id); expect(detail.publishedRevision?.audioAssetId).toBe(a.id); expect(serializeLegacyPodcast(detail.publishedRevision!, detail.legacyId).file_id).toBe(`/legacy-audio/${a.legacyAudioId}-high.mp3`); await publishPodcast(editor, podcast.id, { expectedWorkingVersion: 2 }); detail = await getPodcast(editor, podcast.id); expect(serializeLegacyPodcast(detail.publishedRevision!, detail.legacyId).file_id).toBe(`/legacy-audio/${b.legacyAudioId}-high.mp3`); });

  it("applies 30-day retention to unreferenced audio", async () => { const storage = new MemoryStorage(); const asset = await upload(storage); const created = asset.unreferencedAt!; expect(await purgeEligibleMedia(admin, new Date(created.getTime() + 29 * 86400000), storage)).toEqual({ examined: 0, purged: 0 }); expect(await purgeEligibleMedia(admin, new Date(created.getTime() + 31 * 86400000), storage)).toEqual({ examined: 1, purged: 1 }); expect(storage.files.size).toBe(0); });
});
