"use client";

import { useState, type ChangeEvent } from "react";
import { formatAudioDuration } from "@/modules/media/format";

type MediaReference = { type: string; id: string; name?: string; title?: string; artistId?: string; trackId?: string; episodeId?: string; releaseId?: string; revisionNumber?: number };
type MediaRow = { id: string; kind: "IMAGE" | "AUDIO"; originalFilename: string; compatibilityFilename: string | null; legacyAudioId: string | null; width: number | null; height: number | null; durationMs: number | null; status: string; mimeType: string; byteSize: number; sha256Checksum: string; sourceStorageKey: string; referenceCount: number; references: MediaReference[]; createdAt: string; createdBy: { name: string }; variants: Array<{ variantKey: string; width: number; height: number; byteSize: number; sha256Checksum: string; storageKey: string }> };

export function MediaManager({ initial, role }: { initial: MediaRow[]; role: string }) {
  const [assets, setAssets] = useState(initial); const [selected, setSelected] = useState<MediaRow | null>(initial[0] ?? null); const [filter, setFilter] = useState<"ALL" | "IMAGE" | "AUDIO">("ALL"); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const canUpload = role !== "VIEWER"; const shown = filter === "ALL" ? assets : assets.filter((asset) => asset.kind === filter);
  async function onUpload(event: ChangeEvent<HTMLInputElement>, kind: "IMAGE" | "AUDIO") { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.set("kind", kind); data.set("file", file); setPending(true); setError(""); try { const response = await fetch("/api/admin/media", { method: "POST", body: data }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Upload failed."); window.location.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Upload failed."); setPending(false); } }
  async function retire() { if (!selected) return; setPending(true); const response = await fetch(`/api/admin/media/${selected.id}/actions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "retire" }) }); const body = await response.json(); if (!response.ok) { setError(body.error?.message ?? "Retire failed."); setPending(false); return; } setAssets(assets.map((asset) => asset.id === selected.id ? { ...asset, status: "RETIRED" } : asset)); setSelected({ ...selected, status: "RETIRED" }); setPending(false); }
  return <div className="editor-grid"><section className="panel editor-column"><div className="section-heading"><div><div className="eyebrow">Local library</div><h2>Media assets</h2></div>{canUpload && <div className="button-row"><label className="button primary">{pending ? "Processing…" : "Upload image"}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => onUpload(event, "IMAGE")} disabled={pending} /></label><label className="button">{pending ? "Processing…" : "Upload MP3"}<input hidden type="file" accept="audio/mpeg,.mp3" onChange={(event) => onUpload(event, "AUDIO")} disabled={pending} /></label></div>}</div><label>Kind filter<select aria-label="Kind filter" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="ALL">All</option><option value="IMAGE">Images</option><option value="AUDIO">Audio</option></select></label>{error && <div className="alert error" role="alert">{error}</div>}
    <div className="media-grid">{shown.map((asset) => <button type="button" className="media-card" key={asset.id} onClick={() => setSelected(asset)}>{asset.kind === "IMAGE" ? <img src={`/assets/uploads/files/thumbnails/256/${asset.compatibilityFilename}`} alt="" /> : <span className="audio-tile" aria-hidden="true">♫</span>}<strong>{asset.originalFilename}</strong><small>{asset.kind === "IMAGE" ? `${asset.width}×${asset.height}` : formatAudioDuration(asset.durationMs)} · {(asset.byteSize / 1024).toFixed(1)} KB</small><i className={`status ${asset.status.toLowerCase()}`}>{asset.status}</i><small>{asset.referenceCount} references · {new Date(asset.createdAt).toLocaleDateString()} · {asset.createdBy.name}</small></button>)}</div>
  </section><aside className="preview-column">{selected && <section className="panel preview"><div className="eyebrow">{selected.kind} detail</div>{selected.kind === "IMAGE" ? <img className="detail-artwork" src={`/assets/uploads/files/${selected.compatibilityFilename}`} alt={selected.originalFilename} /> : selected.legacyAudioId && <audio controls preload="metadata" src={`/legacy-audio/${selected.legacyAudioId}-high.mp3`} />}<dl><dt>MediaAsset ID</dt><dd className="mono">{selected.id}</dd><dt>Kind</dt><dd>{selected.kind}</dd><dt>Status</dt><dd>{selected.status}</dd><dt>MIME</dt><dd>{selected.mimeType}</dd>{selected.kind === "IMAGE" ? <><dt>Dimensions</dt><dd>{selected.width}×{selected.height}</dd><dt>Compatibility filename</dt><dd className="mono">{selected.compatibilityFilename}</dd></> : <><dt>Duration</dt><dd>{formatAudioDuration(selected.durationMs)}</dd><dt>Compatibility audio ID</dt><dd className="mono">{selected.legacyAudioId}</dd></>}<dt>Checksum</dt><dd className="mono">{selected.sha256Checksum}</dd><dt>Storage key</dt><dd className="mono">{selected.sourceStorageKey}</dd><dt>References</dt><dd>{selected.referenceCount}</dd></dl>{selected.references.length > 0 && <ul>{selected.references.map((reference) => <li key={`${reference.type}-${reference.id}`}><strong>{reference.type}</strong> — {reference.name ?? reference.title ?? `revision ${reference.revisionNumber}`}</li>)}</ul>}{selected.kind === "IMAGE" && <><h3>Variants</h3>{selected.variants.map((variant) => <p key={variant.variantKey}><strong>{variant.variantKey}</strong><br/><span className="mono">{variant.storageKey}</span><br/>{variant.width}×{variant.height} · {variant.byteSize} bytes<br/><span className="mono">{variant.sha256Checksum}</span></p>)}</>}{role === "ADMIN" && selected.referenceCount === 0 && selected.status !== "RETIRED" && <button className="button danger" onClick={retire} disabled={pending}>Retire</button>}</section>}</aside></div>;
}
