"use client";

import { useState, type ChangeEvent } from "react";
import type { ArtworkOption } from "@/components/artwork-picker";

type MediaReference = { type: string; id: string; name?: string; title?: string; artistId?: string; trackId?: string; episodeId?: string; releaseId?: string; revisionNumber?: number };
type MediaRow = ArtworkOption & { mimeType: string; byteSize: number; sha256Checksum: string; sourceStorageKey: string; referenceCount: number; references: MediaReference[]; createdAt: string; createdBy: { name: string }; variants: Array<{ variantKey: string; width: number; height: number; byteSize: number; sha256Checksum: string; storageKey: string }> };

export function MediaManager({ initial, role }: { initial: MediaRow[]; role: string }) {
  const [assets, setAssets] = useState(initial); const [selected, setSelected] = useState<MediaRow | null>(initial[0] ?? null); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const canUpload = role !== "VIEWER";
  async function onUpload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.set("file", file); setPending(true); setError(""); try { const response = await fetch("/api/admin/media", { method: "POST", body: data }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Upload failed."); window.location.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Upload failed."); setPending(false); } }
  async function retire() { if (!selected) return; setPending(true); const response = await fetch(`/api/admin/media/${selected.id}/actions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "retire" }) }); const body = await response.json(); if (!response.ok) { setError(body.error?.message ?? "Retire failed."); setPending(false); return; } setAssets(assets.map((asset) => asset.id === selected.id ? { ...asset, status: "RETIRED" } : asset)); setSelected({ ...selected, status: "RETIRED" }); setPending(false); }
  return <div className="editor-grid"><section className="panel editor-column"><div className="section-heading"><div><div className="eyebrow">Local library</div><h2>Image assets</h2></div>{canUpload && <label className="button primary">{pending ? "Processing…" : "Upload image"}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={onUpload} disabled={pending} /></label>}</div>{error && <div className="alert error" role="alert">{error}</div>}
    <div className="media-grid">{assets.map((asset) => <button type="button" className="media-card" key={asset.id} onClick={() => setSelected(asset)}><img src={`/assets/uploads/files/thumbnails/256/${asset.compatibilityFilename}`} alt="" /><strong>{asset.originalFilename}</strong><small>{asset.width}×{asset.height} · {(asset.byteSize / 1024).toFixed(1)} KB</small><i className={`status ${asset.status.toLowerCase()}`}>{asset.status}</i><small>{asset.referenceCount} references · {new Date(asset.createdAt).toLocaleDateString()} · {asset.createdBy.name}</small></button>)}</div>
  </section><aside className="preview-column">{selected && <section className="panel preview"><div className="eyebrow">Media detail</div><img className="detail-artwork" src={`/assets/uploads/files/${selected.compatibilityFilename}`} alt={selected.originalFilename} /><dl><dt>MediaAsset ID</dt><dd className="mono">{selected.id}</dd><dt>Status</dt><dd>{selected.status}</dd><dt>MIME</dt><dd>{selected.mimeType}</dd><dt>Dimensions</dt><dd>{selected.width}×{selected.height}</dd><dt>Checksum</dt><dd className="mono">{selected.sha256Checksum}</dd><dt>Compatibility filename</dt><dd className="mono">{selected.compatibilityFilename}</dd><dt>Storage key</dt><dd className="mono">{selected.sourceStorageKey}</dd><dt>References</dt><dd>{selected.referenceCount}</dd></dl>{selected.references.length > 0 && <ul>{selected.references.map((reference) => <li key={`${reference.type}-${reference.id}`}><strong>{reference.type}</strong> — {reference.name ?? reference.title ?? `revision ${reference.revisionNumber}`}</li>)}</ul>}<h3>Variants</h3>{selected.variants.map((variant) => <p key={variant.variantKey}><strong>{variant.variantKey}</strong><br/><span className="mono">{variant.storageKey}</span><br/>{variant.width}×{variant.height} · {variant.byteSize} bytes<br/><span className="mono">{variant.sha256Checksum}</span></p>)}{role === "ADMIN" && selected.referenceCount === 0 && selected.status !== "RETIRED" && <button className="button danger" onClick={retire} disabled={pending}>Retire</button>}</section>}</aside></div>;
}
