"use client";
import { useEffect, useId, useState } from "react";
import type { ReleaseTrackOption } from "./release-editor";
import styles from "./tracks-filters.module.css";
export function ReleaseTracklist({ value, onChange, disabled }: { value: ReleaseTrackOption[]; onChange: (value: ReleaseTrackOption[]) => void; disabled: boolean }) {
  const id = useId(); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [rows, setRows] = useState<ReleaseTrackOption[]>([]); const [picked, setPicked] = useState<ReleaseTrackOption | null>(null); const [active, setActive] = useState(-1); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!open || disabled) return; const controller = new AbortController(); let current = true; const timer = setTimeout(async () => { setLoading(true); try { const r = await fetch(`/api/admin/choices?${new URLSearchParams({ kind: "track", q: query })}`, { signal: controller.signal, cache: "no-store" }); if (!r.ok) throw Error("Could not search Tracks."); const items = await r.json(); if (current) { setRows(items); setError(""); } } catch { if (current && !controller.signal.aborted) setError("Could not search Tracks. Try again."); } finally { if (current) setLoading(false); } }, 250); return () => { current = false; clearTimeout(timer); controller.abort(); }; }, [open, query, disabled]);
  function choose(track: ReleaseTrackOption) { if (value.some(t => t.id === track.id)) return; setPicked(track); setQuery(track.title); setOpen(false); setActive(-1); }
  function move(from: number, to: number) { if (to < 0 || to >= value.length) return; const next = [...value]; const [track] = next.splice(from, 1); next.splice(to, 0, track!); onChange(next); }
  return <section className="track-design-section release-construction"><div className="track-section-heading"><h2>Tracks</h2><p>Add existing Tracks in playback order. Each Track needs an active published version before the Release can be published.</p></div>
    {!disabled && <div className="release-search-row"><div className="release-search-field"><label htmlFor={id}>Add Track</label><div className="track-combobox-control"><input id={id} role="combobox" aria-expanded={open} aria-autocomplete="list" aria-controls={`${id}-list`} aria-activedescendant={open && active >= 0 && rows[active] ? `${id}-${active}` : undefined} autoComplete="off" placeholder="Search track…" value={query} maxLength={200} onFocus={() => setOpen(true)} onBlur={() => setOpen(false)} onChange={e => { setQuery(e.target.value); setOpen(true); setPicked(null); setRows([]); setActive(-1); setError(""); }} onKeyDown={e => { if (e.key === "ArrowDown" || e.key === "ArrowUp") { e.preventDefault(); setOpen(true); setActive(i => Math.max(0, Math.min(rows.length - 1, i + (e.key === "ArrowDown" ? 1 : -1)))); } else if (e.key === "Enter" && open) { e.preventDefault(); if (rows[active]) choose(rows[active]!); } else if (e.key === "Escape") setOpen(false); }} /></div>
      {open && <div className={styles.popup}><ul id={`${id}-list`} role="listbox" aria-label="Track choices">{rows.map((track, i) => <li id={`${id}-${i}`} key={track.id} role="option" aria-selected={picked?.id === track.id} aria-disabled={value.some(t => t.id === track.id)} className={i === active ? styles.active : undefined} onMouseDown={e => e.preventDefault()} onClick={() => choose(track)}><strong>{track.title}</strong><small>{track.primaryArtistName} · {track.labelName}{value.some(t => t.id === track.id) ? " · Already added" : ""}</small></li>)}</ul>{error ? <p role="alert">{error}</p> : <p role="status">{loading ? "Searching…" : !rows.length ? "No matching Tracks." : `${rows.length} results`}</p>}</div>}
    </div><button type="button" className="button" disabled={!picked || value.length >= 500 || value.some(t => t.id === picked.id)} onClick={() => { if (!picked) return; onChange([...value, picked]); setPicked(null); setQuery(""); setRows([]); setOpen(false); }}>Add Track</button></div>}
    <ol className="release-ordered-tracks">{value.map((track, i) => <li key={track.id}><span className="release-position">{i + 1}</span><div><strong>{track.primaryArtistName} — {track.title}</strong><small>{track.labelName}</small>{(!track.publishedRevisionId || !["PUBLISHED", "SCHEDULED"].includes(track.status)) && <small className="blocking-warning">Needs publication before this Release can be published.</small>}{track.changedSinceReleasePublication && <small className="track-change-warning">Track has changed since this Release was published.</small>}</div>{!disabled && <div className="release-order-actions"><button className="button" type="button" aria-label={`Move Track ${i + 1} up`} disabled={i === 0} onClick={() => move(i, i - 1)}>↑</button><button className="button" type="button" aria-label={`Move Track ${i + 1} down`} disabled={i === value.length - 1} onClick={() => move(i, i + 1)}>↓</button><button className="button" type="button" aria-label={`Remove Track ${i + 1}`} onClick={() => onChange(value.filter(t => t.id !== track.id))}>Remove</button></div>}</li>)}</ol>{!value.length && <p className="empty-inline">No Tracks added yet.</p>}
  </section>;
}
