import Link from "next/link";
import { headers } from "next/headers";
import { actorForPage } from "@/lib/session";
import { formatCmsDate } from "@/lib/date";
import { getPodcastFormOptions, listPodcasts } from "@/modules/podcasts/service";

export default async function PodcastsPage({ searchParams }: PageProps<"/admin/podcasts">) {
  const actor = await actorForPage(await headers()); const params = await searchParams; const filters = { q: typeof params.q === "string" ? params.q : undefined, artistId: typeof params.artistId === "string" ? params.artistId : undefined, labelId: typeof params.labelId === "string" ? params.labelId : undefined, status: typeof params.status === "string" ? params.status : undefined };
  const [podcasts, options] = await Promise.all([listPodcasts(actor, filters), getPodcastFormOptions(actor)]);
  return <><section className="page-heading"><div><div className="eyebrow">Content</div><h1>Podcasts</h1><p className="muted">Structured chapters and frozen delivery revisions.</p></div>{actor.role !== "VIEWER" && <Link className="button primary" href="/admin/podcasts/new">Create Podcast</Link>}</section>
    <form className="panel filter-bar"><input name="q" defaultValue={filters.q} placeholder="Search title" /><select name="artistId" defaultValue={filters.artistId ?? ""}><option value="">All Artists</option>{options.artists.map((artist) => <option value={artist.id} key={artist.id}>{artist.name}</option>)}</select><select name="labelId" defaultValue={filters.labelId ?? ""}><option value="">All Labels</option>{options.labels.map((label) => <option value={label.id} key={label.id}>{label.name}</option>)}</select><select name="status" defaultValue={filters.status ?? ""}><option value="">All statuses</option>{["DRAFT","SCHEDULED","PUBLISHED","UNPUBLISHED","ARCHIVED"].map((status) => <option key={status}>{status}</option>)}</select><button className="button">Filter</button></form>
    <section className="panel table-panel podcast-table"><div className="table-row table-head"><span>Podcast</span><span>Primary Artist</span><span>Date</span><span>Label</span><span>Legacy ID</span><span>Chapters</span><span>Status</span><span>Unpublished changes</span><span>Updated</span></div>{podcasts.length === 0 && <div className="empty">No Podcasts match these filters.</div>}{podcasts.map((podcast) => { const changed = !podcast.publishedRevision || podcast.publishedRevision.sourceWorkingVersion !== podcast.workingVersion; return <Link className="table-row" href={`/admin/podcasts/${podcast.id}`} key={podcast.id}><span><strong>{podcast.title}</strong></span><span>{podcast.primaryArtist.name}</span><span>{podcast.episodeDate?.toISOString().slice(0,10) ?? "—"}</span><span>{podcast.label.name}</span><span className="mono">{podcast.legacyId}</span><span>{podcast._count.chapters}</span><span><i className={`status ${podcast.status.toLowerCase()}`}>{podcast.status}</i></span><span>{changed ? "Yes" : "No"}</span><span>{formatCmsDate(podcast.updatedAt)}</span></Link>; })}</section></>;
}
