import Link from "next/link";
import { headers } from "next/headers";
import { ReleaseEditor, type ReleaseEditorData } from "@/components/release-editor";
import { actorForPage } from "@/lib/session";
import { serializeLegacyRelease, serializeLegacyReleaseCompleteTrack } from "@/modules/releases/legacy";
import { getLegacyReleasePreview, getRelease, getReleaseFormOptions, getReleasePreview } from "@/modules/releases/service";

const isoDate = (date: Date | null) => date ? date.toISOString().slice(0, 10) : null;

export default async function ReleasePage({ params }: PageProps<"/admin/releases/[id]">) {
  const actor = await actorForPage(await headers()); const release = await getRelease(actor, (await params).id); const [options, canonicalPreview, proposedLegacyPreview] = await Promise.all([getReleaseFormOptions(actor, { primaryArtistId: release.primaryArtistId, secondaryArtistId: release.secondaryArtistId, labelId: release.labelId, trackIds: release.tracks.map(({ trackId }) => trackId) }), getReleasePreview(actor, release.id), getLegacyReleasePreview(actor, release.id)]);
  const published = release.publishedRevision; const publishedLegacyComplete = published ? { releasecomplete: { "0": serializeLegacyRelease(published, release.legacyId, "complete"), tracks: published.tracks.map(({ trackRevision }) => serializeLegacyReleaseCompleteTrack(trackRevision, trackRevision.track.legacyId)) }, base_cover_folder: "/1440/", main_cover_folder: "/assets/uploads/files" } : null;
  const data: ReleaseEditorData = {
    id: release.id, legacyId: release.legacyId, title: release.title, primaryArtistId: release.primaryArtistId, secondaryArtistId: release.secondaryArtistId, labelId: release.labelId, releaseDate: isoDate(release.releaseDate), spotifyUrl: release.spotifyUrl, beatportUrl: release.beatportUrl, traxsourceUrl: release.traxsourceUrl, bandcampUrl: release.bandcampUrl, appleMusicUrl: release.appleMusicUrl, soundcloudUrl: release.soundcloudUrl, status: release.status, workingVersion: release.workingVersion, scheduledFor: release.scheduledFor?.toISOString() ?? null,
    publishedRevision: published ? { id: published.id, revisionNumber: published.revisionNumber, sourceWorkingVersion: published.sourceWorkingVersion, title: published.title, createdAt: published.createdAt.toISOString(), trackCount: published.tracks.length } : null,
    scheduledRevision: release.scheduledRevision ? { id: release.scheduledRevision.id, revisionNumber: release.scheduledRevision.revisionNumber, sourceWorkingVersion: release.scheduledRevision.sourceWorkingVersion, title: release.scheduledRevision.title, createdAt: release.scheduledRevision.createdAt.toISOString(), trackCount: release.scheduledRevision.tracks.length } : null,
    revisions: release.revisions.map((revision) => ({ id: revision.id, revisionNumber: revision.revisionNumber, sourceWorkingVersion: revision.sourceWorkingVersion, title: revision.title, createdAt: revision.createdAt.toISOString(), trackCount: revision.tracks.length })), auditLogs: release.auditLogs.map((log) => ({ id: log.id, action: log.action, createdAt: log.createdAt.toISOString(), actor: log.actor ? { name: log.actor.name } : null })), trackIds: release.tracks.map(({ trackId }) => trackId),
  };
  return <><Link className="back-link" href="/admin/releases">← Releases</Link><section className="page-heading"><div><div className="eyebrow">Release record</div><h1>{release.title}</h1><p className="muted">Working membership and exact immutable Track delivery snapshots.</p></div></section><ReleaseEditor release={data} role={actor.role} artists={options.artists.map(({ id, name, legacyId }) => ({ id, name, legacyId }))} labels={options.labels.map(({ id, name, active }) => ({ id, name, active }))} tracks={options.tracks.map((track) => ({ id: track.id, title: track.title, legacyId: track.legacyId, status: track.status, primaryArtistName: track.publishedRevision?.primaryArtistName ?? track.primaryArtist.name, labelName: track.label.name, publishedRevisionId: track.publishedRevisionId, publishedRevisionNumber: track.publishedRevision?.revisionNumber ?? null }))} canonicalPreview={canonicalPreview} proposedLegacyPreview={proposedLegacyPreview} publishedLegacyComplete={publishedLegacyComplete} /></>;
}
